import sys
from AX12A import *

if len(sys.argv) != 3:
    print("Usage: python3 interrogate.py TTY_NAME DEVICE_ID");
    quit(1)

ax12a = AX12A(sys.argv[1], int(sys.argv[2]))
print("%30s: %s" % ("Model Number", str(ax12a.getModelNumber())))
print("%30s: %s" % ("Firmware Version", str(ax12a.getFirmwareVersion())))
print("%30s: %s" % ("Id", str(ax12a.getId())))
print("%30s: %s" % ("Baud Rate", str(ax12a.getBaudRate())))
print("%30s: %s" % ("Return Delay Time", str(ax12a.getReturnDelayTime())))
print("%30s: %s" % ("Cw Angle Limit", str(ax12a.getCwAngleLimit())))
print("%30s: %s" % ("Ccw Angle Limit", str(ax12a.getCcwAngleLimit())))
print("%30s: %s" % ("Temperature Limit", str(ax12a.getTemperatureLimit())))
print("%30s: %s" % ("Min Voltage Limit", str(ax12a.getMinVoltageLimit())))
print("%30s: %s" % ("Max Voltage Limit", str(ax12a.getMaxVoltageLimit())))
print("%30s: %s" % ("Max Torque", str(ax12a.getMaxTorque())))
print("%30s: %s" % ("Status Return Level", str(ax12a.getStatusReturnLevel())))
print("%30s: %s" % ("Alarm LED", str(ax12a.getAlarmLed())))
print("%30s: %s" % ("Shutdown", str(ax12a.getShutdown())))
print("%30s: %s" % ("Torque Enable", str(ax12a.getTorqueEnable())))
print("%30s: %s" % ("LED", str(ax12a.getLed())))
print("%30s: %s" % ("Cw Compliance Margin", str(ax12a.getCwComplianceMargin())))
print("%30s: %s" % ("Ccw Compliance Margin", str(ax12a.getCcwComplianceMargin())))
print("%30s: %s" % ("Cw Compliance Slope", str(ax12a.getCwComplianceSlope())))
print("%30s: %s" % ("Ccw Compliance Slope", str(ax12a.getCcwComplianceSlope())))
print("%30s: %s" % ("Goal Position", str(ax12a.getGoalPosition())))
print("%30s: %s" % ("Moving Speed", str(ax12a.getMovingSpeed())))
print("%30s: %s" % ("Torque Limit", str(ax12a.getTorqueLimit())))
print("%30s: %s" % ("Present Position", str(ax12a.getPresentPosition())))
print("%30s: %s" % ("Present Speed", str(ax12a.getPresentSpeed())))
print("%30s: %s" % ("Present Load", str(ax12a.getPresentLoad())))
print("%30s: %s" % ("Present Voltage", str(ax12a.getPresentVoltage())))
print("%30s: %s" % ("Present Temperature", str(ax12a.getPresentTemperature())))
print("%30s: %s" % ("Registered Instruction", str(ax12a.getRegisteredInstruction())))
print("%30s: %s" % ("Moving", str(ax12a.getMoving())))
print("%30s: %s" % ("Lock", str(ax12a.getLock())))
print("%30s: %s" % ("Punch", str(ax12a.getPunch())))
