import sys
from AX12A import *

if len(sys.argv) != 3:
    print("Usage: python3 interrogate.py TTY_NAME DEVICE_ID");
    quit(1)

ax12a = AX12A(sys.argv[1], int(sys.argv[2]))
print("%30s: %s" % ("Model Number", ax12a.getModelNumber()))
print("%30s: %s" % ("Firmware Version", ax12a.getFirmwareVersion()))
print("%30s: %s" % ("Id", ax12a.getId()))
print("%30s: %s" % ("Baud Rate", ax12a.getBaudRate()))
print("%30s: %s" % ("Return Delay Time", ax12a.getReturnDelayTime()))
print("%30s: %s" % ("Cw Angle Limit", ax12a.getCwAngleLimit()))
print("%30s: %s" % ("Ccw Angle Limit", ax12a.getCcwAngleLimit()))
print("%30s: %s" % ("Temperature Limit", ax12a.getTemperatureLimit()))
print("%30s: %s" % ("Min Voltage Limit", ax12a.getMinVoltageLimit()))
print("%30s: %s" % ("Max Voltage Limit", ax12a.getMaxVoltageLimit()))
print("%30s: %s" % ("Max Torque", ax12a.getMaxTorque()))
print("%30s: %s" % ("Status Return Level", ax12a.getStatusReturnLevel()))
print("%30s: %s" % ("Alarm LED", ax12a.getAlarmLed()))
print("%30s: %s" % ("Shutdown", ax12a.getShutdown()))
print("%30s: %s" % ("Torque Enable", ax12a.getTorqueEnable()))
print("%30s: %s" % ("LED", ax12a.getLed()))
print("%30s: %s" % ("Cw Compliance Margin", ax12a.getCwComplianceMargin()))
print("%30s: %s" % ("Ccw Compliance Margin", ax12a.getCcwComplianceMargin()))
print("%30s: %s" % ("Cw Compliance Slope", ax12a.getCwComplianceSlope()))
print("%30s: %s" % ("Ccw Compliance Slope", ax12a.getCcwComplianceSlope()))
print("%30s: %s" % ("Goal Position", ax12a.getGoalPosition()))
print("%30s: %s" % ("Moving Speed", ax12a.getMovingSpeed()))
print("%30s: %s" % ("Torque Limit", ax12a.getTorqueLimit()))
print("%30s: %s" % ("Present Position", ax12a.getPresentPosition()))
print("%30s: %s" % ("Present Speed", ax12a.getPresentSpeed()))
print("%30s: %s" % ("Present Load", ax12a.getPresentLoad()))
print("%30s: %s" % ("Present Voltage", ax12a.getPresentVoltage()))
print("%30s: %s" % ("Present Temperature", ax12a.getPresentTemperature()))
print("%30s: %s" % ("Registered Instruction", ax12a.getRegisteredInstruction()))
print("%30s: %s" % ("Moving", ax12a.getMoving()))
print("%30s: %s" % ("Lock", ax12a.getLock()))
print("%30s: %s" % ("Punch", ax12a.getPunch()))
